### ISSUE TITLE
How to change fame rate pico-wizard-imx8m-mini with 10.1 " panel 

### ISSUE THREAD

**Issue by ChatchaiBuekban** [technexion-android/cookers#29] opened 2021-02-02 08:34 UTC
Hi,

I'm not sure about pico-wizard-imx8m-mini with a 10.1 " panel default frame rate?, because I see the display not smooth.  how to increase them?

Thanks.

**Comment by wigcheng** [comment] 2021-02-02 08:42
Could you take a video to youtube or provide me the test video file if possible? I have no idea how not smooth.

Try to increase the CMA size of <source code>/device/fsl/imx8m/pico-imx8mm/BoardConfig.mk
124 CMASIZE=736M
to
124 CMASIZE=960M

And try again, 1920x1200 resolution could be too heavy loading with high data rate video file, I'll check it later.
Thanks a lot

**Comment by wigcheng** [comment] 2021-02-02 08:43
Also want to know what's your DDR memory size of PICO-IMX8MM? Thanks

**Comment by ChatchaiBuekban** [comment] 2021-02-02 10:12
Thanks for your reply,

I'm using PICO-IMX8MM 4GB Memory, I just look at the home screen, not sure because of refresh rate or LCD backlight

**Comment by wigcheng** [comment] 2021-02-03 11:01
I'm trying to reproduce issue here, but need check with you again about your display issue:

1. Video play is very good performance.
2. Only boot animation not smoothly because 1920x1200 is maximum limitation of MIPI for PICO-IMX8MM, if you think it's not okay, you take out that animation manually.
3. home screen looks smoothly when I swipe it, but I saw a bit **flicking bug on the screen**, do you mean this flicking issue ??? I need detail description if possible.

Thanks a lot

**Comment by wigcheng** [comment] 2021-02-04 02:53
Just tweaked a new timing for this panel, looks perfect no matter boot animation or home screen controlling.
Also uploaded the commit already, please do 'repo sync' to update kernel repo there, recompile and try again, should be works!

Don't forget close this ticket if works :)

**Comment by ChatchaiBuekban** [comment] 2021-02-04 03:02
Touch screen I found issue too and I have to fix dts file for correct touch screen driver and I will try to build with your fix later.

Now, It's ok if you confirm video can play good performance.

** Screen not smooth that I mean I see a little bit ripple or vibrating (not sure in pixel or backlight) and more when I increase backlight to maximum.

Maybe just problem only my screen hardware, I will buy to try compare later.

Thanks.

**Comment by wigcheng** [comment] 2021-02-04 03:06
** Screen not smooth that I mean I see a little bit ripple or vibrating (not sure in pixel or backlight) and more when I increase backlight to maximum.

About this problem, it's a bug which I mention as above, just fixed, please update your kernel repository (<source>/vendor/nxp-opensource/kernel_imx), thanks!

https://github.com/technexion-android/kernel_imx/commit/f300efd38557981f1f197807068e2a0240fb3309

**Comment by ChatchaiBuekban** [comment] 2021-02-04 03:11
Thanks a lot.

I will sync repo and try latter.

**Closed as completed** 2021-02-04 03:32 UTC
Labels: question
